### ISSUE TITLE
File organization

### ISSUE THREAD

**Issue by Invertex** [kpids/bmod#1]
Hi, really simple and useful plugin you made here!

If I could make a suggestion though, right now the file layout for this repo will pollute people's project ROOT, which is kinda bad practice and is how conflicts end up happening.

I would really recommend moving the example files you have in the root to something like `root/addons/bmod_examples/`
This way it won't pollute on default or automated installations and future updates of the addon, and it gives a singular folder for people to also uncheck inclusion of the example assets.

Thanks!

**Comment by Toldoven** [comment]
Hi! I think the proper way to address this issue is to edit `.gitattributes` so that Godot Asset Library ignores folders and files that are not part of the addon: https://docs.godotengine.org/en/latest/community/asset_library/submitting_to_assetlib.html#recommendations

I thought that I already did it but turns out I didn't. So I edited it and the new version is on review in Godot Asset Store. Should be up as soon as it's approved. Thanks for the feedback!
